apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: guess-game
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
       - name: frontend
         image: leandrolbbernardes/pucminas:frontend-react-guess-game
         resources:
           requests:
             memory: "10Mi"
             cpu: "10m"
           limits:
             memory: "256Mi"
             cpu: "250m"
         volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          secret:
            secretName: nginx-config