apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-pv
  namespace: guess-game
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres