apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-pv
  namespace: guess-game
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres